name: ufin_admin_system
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  
  # State Management
  riverpod: ^2.5.1
  flutter_riverpod: ^2.5.1
  
  # Routing
  go_router: ^14.2.0
  
  # Secure Storage
  flutter_secure_storage: ^9.2.2
  
  # Environment Variables
  flutter_dotenv: ^5.2.1
  
  # HTTP
  dio: ^5.5.0
  
  # Logging
  logger: ^2.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - .env
